### ISSUE TITLE
Extended error information for `decompile_func()` not available

### ISSUE THREAD

**Issue by 0xdea** [binarly-io/idalib#21]
At the moment, `decompile_func()` returns an `Option<cxx::UniquePtr<cfuncptr_t>>`. This means that if the decompiler is generally available (i.e., `decompiler_available()` is `true`), but the license in use doesn't include a suitable decompiler for the current binary file, we would get a `None` result with no indication of the reason for the failure.

For instance, in [haruspex](https://github.com/0xdea/haruspex) I'm forced to do something like the following to catch this type of failure:
```rust
    // Remove output directory and return an error in case no functions were decompiled
    if COUNTER.load(Ordering::Relaxed) == 0 {
        fs::remove_dir(&dirpath)?;
        return Err(anyhow::anyhow!(
            "no functions were decompiled, check your license and input file"
        ));
    }
```

It would be convenient to be able to get extended error information (see `hexrays_failure_t` and `merror_t` in `include/hexrays.hpp` in the IDA SDK) to catch "no license available" and other error cases. Thanks!

**Comment by xorpse** [comment]
That’s not ideal at all :). I’ll see about updating the API to report errors rather than silently failing.
